"""Host-runner rejection codes (slice-00-06).

SPIKE-EXPERIMENTAL marker:
DISPOSITION: KEEP_MARKED_EVIDENCE
"""

from __future__ import annotations

DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
UNSUPPORTED_RUNTIME = "UNSUPPORTED_RUNTIME"
