"""Host-runner rejection codes (slice-00-06).

SPIKE-EXPERIMENTAL marker:
DISPOSITION: DELETE_UNLESS_ADOPTED_BY_00-07
"""

from __future__ import annotations

DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
UNSUPPORTED_RUNTIME = "UNSUPPORTED_RUNTIME"
