"""Typed evaluator outcomes.

SPIKE-EXPERIMENTAL marker:
DISPOSITION: DELETE_UNLESS_ADOPTED_BY_PHASE_01
"""

ACCEPTED = "ACCEPTED"
EMPTY_REQUIREMENT = "EMPTY_REQUIREMENT"
INVALID_TRANSITION = "INVALID_TRANSITION"

__all__ = ["ACCEPTED", "EMPTY_REQUIREMENT", "INVALID_TRANSITION"]
